config/routes.rb
TheGreyGirl::Application.routes.draw do
  resources :images

  devise_for :admins
  get "home/index"

  root 'blogs#index'
  
  resources :home
  resources :blogs do
    collection do
      get 'current'
      get 'archive'
    end
  end
  
  namespace :admin do
    resources :blogs do
      put 'publish' => "drafts#update"
    end
    resources :drafts
  end

  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_drafts
  has_one :gallery
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  belongs_to :blog
  has_many :images, :dependent => :destroy
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :gallery
  has_attached_file :file, :styles => { :medium => "300x300>", :thumb => "100x100>" }, 
                    :url  => "/images/:id/:filename", 
                    :path => ":rails_root/public/images/:id/:filename", 
                    :default_url => "/images/:style/missing.png"
  do_not_validate_attachment_file_type :file
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_filter :authenticate_admin!
end

app/controllers/admin/blogs_controller.rb
class Admin::BlogsController < Admin::BaseController
  before_filter :find_blog,  :only => [:show, :edit, :update, :destroy]
  before_filter :reify_blog, :only => [:show, :edit]
  
  def index
    @blogs = Blog.live.order(id: :desc)
    @blogs.each { |blog| blog.draft.reify if blog.draft? }
  end
  
  def show
  end
  
  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    
    if @blog.draft_creation
      flash[:success] = 'A draft of the new blog was saved successfully.'
      redirect_to admin_blogs_path
    else
      flash[:error] = 'There was an error creating the blog. Please review the errors below and try again.'
      render :new
    end
  end

  def update    
    @blog.attributes = blog_params

    # Instead of calling `update_attributes`, you call `draft_update` to save it as a draft
    if @blog.draft_update
      flash[:success] = 'A draft of the blog update was saved successfully.'
      redirect_to admin_blogs_path
    else
      flash[:error] = 'There was an error updating the blog. Please review the errors below and try again.'
      render :edit
    end
  end

  def edit
  end

  def destroy
    @blog.draft_destroy
    flash[:success] = 'The blog was moved to the trash.'
    redirect_to admin_blogs_path
  end

  private
    def find_blog
      @blog = Blog.live.find(params[:id])
    end

    # If the widget has a draft, load that version of it
    def reify_blog
      @blog = @blog.draft.reify if @blog.draft?
    end
    
    def blog_params
      params.require(:blog).permit(:title, :text)
    end
end

app/controllers/admin/drafts_controller.rb
class Admin::DraftsController < Admin::BaseController
  before_filter :find_draft, :only => [:show, :update, :destroy]

  def index
    @drafts = Draftsman::Draft.includes(:item).order('updated_at DESC')
  end

  def show
  end

  # Post draft ID here to publish it
  def update
    # Call `draft_publication_dependencies` to check if any other drafted records should be published along with this
    # `@draft`.
    @dependencies = @draft.draft_publication_dependencies

    # If you would like to warn the user about dependent drafts that would need to be published along with this one, you
    # would implement an `app/views/drafts/update.html.erb` view template. In that view template, you could list the
    # `@dependencies` and show a button posting back to this action with a name of `commit_publication`. (The button's
    # being clicked indicates to your application that the user accepts that the dependencies should be published along
    # with the `@draft`, thus avoiding orphaned records).
    if @dependencies.empty? && params[:commit_publication]
      @draft.publish!
      flash[:success] = 'The draft was published successfully.'
      redirect_to admin_blogs_path
    else
      # Renders `app/views/drafts/update.html.erb`
    end
  end

  # Post draft ID here to revert it
  def destroy
    # Call `draft_reversion_dependencies` to check if any other drafted records should be reverted along with this
    # `@draft`.
    @dependencies = @draft.draft_reversion_dependencies

    # If you would like to warn the user about dependent drafts that would need to be reverted along with this one, you
    # would implement an `app/views/drafts/destroy.html.erb` view template. In that view template, you could list the
    # `@dependencies` and show a button posting back to this action with a name of `commit_reversion`. (The button's
    # being clicked indicates to your application that the user accepts that the dependencies should be reverted along
    # with the `@draft`, thus avoiding orphaned records).
    if @dependencies.empty? || params[:commit_reversion]
      @draft.revert!
      flash[:success] = 'The draft was reverted successfully.'
      redirect_to admin_drafts_path
    else
      # Renders `app/views/drafts/destroy.html.erb`
    end
  end

private

  # Finds draft by `params[:id]`.
  def find_draft
    if params[:id]
      @draft = Draftsman::Draft.find(params[:id])
    elsif params[:blog_id]
      @draft = Blog.find(params[:blog_id]).draft
    end
  end
end

app/controllers/admin/galleries_controller.rb
class Admin::GalleriesController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def index
    @blogs = Blog.published.order(id: :desc).page(params[:page]).per(5)
    @blogs.reject{ |blog| blog.trashed? }
  end
  
  def archive
    @blogs = Blog.published.order(id: :desc)
    @blogs.reject{ |blog| blog.trashed? }
  end

  def current
    @blog = Blog.published.last
    redirect_to @blog
  end
  
  def show
    @blog = Blog.published.find(params[:id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @images = Image.all
    respond_with(@images)
  end

  def show
    respond_with(@image)
  end

  def new
    @image = Image.new
    respond_with(@image)
  end

  def edit
  end

  def create
    @image = Image.new(image_params)
    @image.save
    respond_with(@image)
  end

  def update
    @image.update(image_params)
    respond_with(@image)
  end

  def destroy
    @image.destroy
    respond_with(@image)
  end

  private
    def set_image
      @image = Image.find(params[:id]) #if params[:id].numeric?
    end

    def image_params
      params[:image]
    end
end

class String
  def numeric?
    Float(self) != nil rescue false
  end
end

app/helpers/admin/blogs_helper.rb
module Admin::BlogsHelper
end

app/helpers/admin/drafts_helper.rb
module Admin::DraftsHelper
end

app/helpers/admin/galleries_helper.rb
module Admin::GalleriesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/admin/blogs/edit.html.erb
<h1>Editing blog</h1>
 
<%= form_for :blog, url: admin_blog_path(@blog), method: :patch do |f| %>
  <% if @blog.errors.any? %>
  <div id="error_explanation">blog
    <h2><%= pluralize(@blog.errors.count, "error") %> prohibited
      this blog from being saved:</h2>
    <ul>
    <% @blog.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', admin_blogs_path %>

app/views/admin/blogs/index.html.erb
<table>
    <tr>
      <th>Title</th>
      <th>Published</th>
    </tr>
  <% @blogs.each do |blog| %>
  <% if blog %>
    <tr class="<%= blog.published? ? "published" : "draft" %>">
      <td><%= link_to blog.title, admin_blog_path(blog) %></td>
      <td><%= blog.published_at %></td>
      <td>
        <div class="btn-group">
          <%= link_to edit_admin_blog_path(blog), class: "btn btn-default" do %>
            <i class="glyphicon glyphicon-pencil"></i>
          <% end %>
          <%= link_to admin_blog_path(blog), method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-default" do %>
            <i class="glyphicon glyphicon-trash"></i>
          <% end %>
          <%= link_to admin_blog_publish_path(:blog_id => blog.id, :commit_publication => true), method: :put, data: { confirm: 'Are you ready to publish?'}, class: "btn btn-default" do %>
            <i class="glyphicon glyphicon-globe"></i>
          <% end %>
        </div>
      </td>
    </tr>
  <% end %>
  <% end %>
</table>

app/views/admin/blogs/new.html.erb
<h1>New Blog Post</h1>

<%= form_for :blog, url: admin_blogs_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', admin_blogs_path %>

app/views/admin/blogs/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @blog.text %>
</p>

<%= link_to 'Edit', edit_admin_blog_path(@blog) %>
<%= link_to 'Destroy', admin_blog_path(@blog), method: :destroy, data: { confirm: 'Are you sure?'} %>

app/views/admin/drafts/index.html.erb
<table>
    <tr>
      <th>Title</th>
      <th>Published</th>
    </tr>
  <% @drafts.each do |draft| %>
    <tr>
      <td><%= link_to draft.blog.title, admin_draft_path(draft) %></td>
      <td><%= draft.blog.published_at %></td>
      <td>
        <div class="btn-group">
          <%= link_to edit_admin_draft_path(draft), class: "btn btn-default" do %>
            <i class="glyphicon glyphicon-pencil"></i>
          <% end %>
          <%= link_to admin_draft_path(draft), method: :destroy, data: { confirm: 'Are you sure?'}, class: "btn btn-default" do %>
            <i class="glyphicon glyphicon-trash"></i>
          <% end %>
          <%= link_to admin_draft_path(blog), controller: "drafts", action: "update", id: draft.id, data: { confirm: 'Are you ready to publish?'}, class: "btn btn-default" do %>
            <i class="glyphicon glyphicon-globe"></i>
          <% end %>
        </div>
      </td>
    </tr>
  <% end %>
</table>

app/views/admin/drafts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @draft.blog.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @draft.blog.text %>
</p>

app/views/blogs/archive.html.erb
<table>
  <tr>
    <th>Title</th>
  </tr>
 
  <% @blogs.each do |blog| %>
    <tr>
      <td><%= blog.title %></td>
      <td><%= link_to 'Show', blog_path(blog) %></td>
    </tr>
  <% end %>
</table>

app/views/blogs/directory.html.erb
<%= link_to 'New blog', new_blog_path if admin_signed_in? %>
 
<table>
  <tr>
    <th>Title</th>
  </tr>
 
  <% @blogs.each do |blog| %>
    <tr>
      <td><%= blog.title %></td>
      <td><%= link_to 'Show', blog_path(blog) %></td>
      <td><%= link_to 'Edit', edit_blog_path(blog) if admin_signed_in? %></td>
      <td><%= link_to 'Destroy', blog_path(blog), method: :delete, data: { confirm: 'Are you sure?'} if admin_signed_in? %></td>
    </tr>
  <% end %>
</table>

app/views/blogs/index.html.erb
<div class = "row">
<% @blogs.each do |blog| %>
  <h2><%= blog.title %></h2>
  <p><span class="glyphicon glyphicon-time"></span>  <%= blog.published_at %></p>
  <hr>
  <img src="http://placekitten.com/g/300/500"></img>
  <img src="http://placekitten.com/g/300/500"></img>
  <img src="http://placekitten.com/g/300/500"></img>
  <hr>
  <p><%= blog.text %></p>
  <hr>
<% end %>
</div>

<%= paginate @blogs %>

app/views/blogs/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @blog.text %>
</p>

app/views/home/index.html.erb
<h1>The Grey Girl</h1>

app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<h1>Listing images</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TheGreyGirl" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div class="navbar navbar-default navbar-fixed-top">

        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to 'TheGreyGirl', blogs_path, :class => 'navbar-brand' %>
          </div>
          <div id="navbar" class="nav-collapse">
            <ul class="nav navbar-nav">
             <li><%= link_to "Archive", archive_blogs_path  %></li>
             <li><%= link_to "New Post", new_admin_blog_path if admin_signed_in? %></li>
             <li><%= link_to "Drafts", admin_blogs_path if admin_signed_in?  %></li>
            </ul>
            <p class="navbar-text pull-right">
              <% if admin_signed_in? %>
                Logged in as <strong><%= current_admin.email %></strong>.
                <%= link_to 'Edit profile', edit_admin_registration_path, :class => 'navbar-link' %> |
                <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %>
                <% end %>
            </p>
          </div>
        </div>

    </div>
    <div class="container">
      <p>
        <%= flash[:success] unless flash[:success].blank? %>
        <%= flash[:error] unless flash[:error].blank? %>
      </p>

		   <%= yield %>
      <footer>
        <p>&copy; TheGreyGirl 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>